language: ruby
rvm:
  - 2.4.1

before_script:
 - chmod +x ./scripts/cibuild.sh

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./scripts/cibuild.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false

cache: bundler