collections:
  projects:
    output: true
    permalink: /project_info/:name

author:
  name: Alex Studer
  twitter: studer_alex

twitter:
  username: studer_alex
  card: summary

exclude: [ "vendor/", "Gemfile", "Gemfile.lock" ]

navigation:
- name: Home
  url: /
- name: Projects
  url: /projects
- name: Posts
  url: /posts

# paginate: 5
# paginate_path: "/posts/:num/"
title: "Alex Studer"
avatar: "https://avatars0.githubusercontent.com/u/1904587?s=256&v=4"
url: "https://alex.studer.dev"
permalink: /:categories/:year/:month/:day/:title

plugins:
- jekyll-feed
- jekyll-mentions
- jekyll-paginate
- jekyll-redirect-from
- jekyll-seo-tag