collections:
  projects:
    output: true
    permalink: /project_info/:name

exclude: [vendor]

navigation:
- name: Home
  url: /
- name: Projects
  url: /projects
- name: Posts
  url: /posts

paginate: 5
paginate_path: "/posts/:num/"
title: "Alex Studer"
url: "https://alex.studer.dev"

plugins:
- jekyll-feed
- jekyll-mentions
- jekyll-paginate
- jekyll-redirect-from
